[package]
name = "ncg_min"
version = "0.1.0"
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
num = "*"

[dev-dependencies]
quickcheck = "*"
gnuplot = "*"
