[package]
name = "ncg_min"
version = "0.1.0"
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
ndarray = "0.11"
num-traits = "0.1.37"

[dev-dependencies]
quickcheck = "0.6"
gnuplot = "0.0.24"
