[package]
name = "ncg_min"
version = "0.1.0"
authors = ["Norbert Pozar <bertapozar@gmail.com>"]
license = "MIT"
readme = "README.md"

[dependencies]
ndarray = "0.9.1"
num-traits = "0.1.37"

[dev-dependencies]
quickcheck = "*"
gnuplot = "*"
